### ISSUE TITLE
Does not start custom instance.

### ISSUE THREAD

**Issue by kruug** [HearthProject/OneClient#47] opened 2017-08-29 20:43 UTC
Client Version: 0.0.2.101
OS: Windows 10 x64
Java Version: 8u144

Created new instance, downloaded mods manually and dropped in Mods folder.  Click the "Play" button, enter Minecraft credentials.

One Client goes into "Not Responding" and cursor goes into the "working" wheel.  After about 4-5 seconds, One Client is responding again, but no Minecraft instance launches.

**Comment by kruug** [comment] 2017-08-29 20:52
Appears to be an issue with the Instance Name field.

Entering a name like "Let's Play!" results in a "File Not Found" error.  Maybe due to erroneous characters (such as ' or !) or the space.  Consider surrounding instance paths in "".

**Comment by primetoxinz** [comment] 2017-08-31 01:41
Need more information on this as, at least on linux, I cannot reproduce it.

**Comment by kruug** [comment] 2017-08-31 02:55
What information would you like?

**Comment by primetoxinz** [comment] 2017-08-31 02:57
If you still have the OneClient/log.txt that would be helpful

**Comment by kruug** [comment] 2017-08-31 03:23
I'll try and recreate the issue tomorrow, for I am not currently at my laptop.

**Comment by kruug** [comment] 2017-08-31 13:52
[OneClient_FileNotFound.txt](https://github.com/HearthProject/OneClient/files/1267274/OneClient_FileNotFound.txt)

**Comment by modmuss50** [comment] 2017-08-31 20:03
Fixed in the next version.

**Comment by modmuss50** [comment] 2017-08-31 20:03
thanks to @primetoxinz 👍

**Closed by modmuss50** 2017-08-31 20:03 UTC
