### ISSUE TITLE
Allow text input for allocated memory in Settings (quality of life)

### ISSUE THREAD

**Issue by jjenco** [HearthProject/OneClient#31] opened 2017-08-26 22:48 UTC
With the current slider, it's difficult to zero in on an exact value for memory allocation (for instance, 6GB exactly instead of 5.97GB or 6.02GB).  It would be nice to have a text input field so I can manually type in how many GB (or MB) of memory to give to Minecraft.

Alternatively, having the slider only adjust in increments of 0.25GB (similar to how the FTB launcher works) would still provide granular control over memory allocation while giving us the ability to zero in on an even value.

**Comment by modmuss50** [comment] 2017-08-27 10:52
Duplicate of #30

**Closed by modmuss50** 2017-08-27 10:52 UTC
Labels: enhancement
